name: Android Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"

      # 3. Install Android SDK, NDK, and CMake
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmake-version: 3.18.1
          ndk-version: 29.0.14033849

      # 4. Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Create .env file from secrets
      - name: Create .env file
        run: |
          echo "ANILIST_CLIENT_ID=${{ secrets.ANILIST_CLIENT_ID }}" >> .env
          echo "ANILIST_CLIENT_SECRET=${{ secrets.ANILIST_CLIENT_SECRET }}" >> .env
          echo "API_URL=${{ secrets.API_URL }}" >> .env
        shell: bash

      # 6. Build APKs (per ABI split)
      - name: Build APK (split per ABI)
        run: flutter build apk --release --split-per-abi

      # 7. Upload APKs to GitHub Release
      - name: Upload APKs to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
